import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import style from "./../styles/style.module.css";
import Sidebar from "@/layout/sidebar/sidebar";
import Header from "@/layout/header/header";

import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const router = useRouter();
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <section className={style.layout}>
          <Sidebar />
          <div style={{ width: "100%" }}>
            <Header />
            <div style={{ padding: 24 }}>{children}</div>
          </div>
        </section> */}
        <Sidebar />
        <section className={styles.main}>
          <Header />
          {children}
        </section>
      </body>
    </html>
  );
}
