import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/layout/sidebar/sidebar";
import Header from "@/layout/header/header";
import { GlobalContextProvider } from "@/context/store";
import Main from "@/layout/main/main";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Sidebar />
          <Main>
            <Header />
            <section className="content">{children}</section>
          </Main>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
